---
apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: selfsigning-issuer
spec:
  selfSigned: {}
---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: minimal-webhook
spec:
  secretName: minimal-webhook
  dnsNames:
    - minimal-webhook.default.svc
  issuerRef:
    name: selfsigning-issuer
    kind: ClusterIssuer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minimal-webhook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minimal-webhook
  template:
    metadata:
      labels:
        app: minimal-webhook
    spec:
      containers:
        - name: minimal-webhook
          image: makkes/minimal-webhook:dev
          volumeMounts:
            - name: tls-cert
              mountPath: "/tls/cert"
              readOnly: true
          ports:
            - containerPort: 443
      volumes:
        - name: tls-cert
          secret:
            secretName: minimal-webhook
---
apiVersion: v1
kind: Service
metadata:
  name: minimal-webhook
spec:
  selector:
    app: minimal-webhook
  ports:
    - port: 443
      targetPort: 443
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: minimal-webhook
  annotations:
    certmanager.k8s.io/inject-ca-from: default/minimal-webhook
webhooks:
  - name: minimal-webhook.example.org
    sideEffects: None
    admissionReviewVersions: ["v1", "v1beta1"]
    clientConfig:
      service:
        name: minimal-webhook
        namespace: default
        port: 443
    rules:
      - apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
        operations: ["CREATE"]
